spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: dbs3cr3t
        testWhileIdle: true
        username: nerd
        validationQuery: SELECT 1
    jpa:
        hibernate:
            ddl-auto: update
            naming:
              strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
    messages:
        basename: BindingErrorMessages

application:
    perPageLimit: 10
