spring:
  profiles:
    active: test
  datasource:
    url: jdbc:mysql://localhost:3306/bbuddytest?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8080
